// Code generated by "stringer -type Color,Waveform"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Transparent-0]
	_ = x[Black-1]
	_ = x[Gray-2]
	_ = x[Red-3]
	_ = x[Pink-4]
	_ = x[DarkBrown-5]
	_ = x[Brown-6]
	_ = x[Orange-7]
	_ = x[Yellow-8]
	_ = x[Green-9]
	_ = x[LightGreen-10]
	_ = x[DarkBlue-11]
	_ = x[Blue-12]
	_ = x[LightBlue-13]
	_ = x[SkyBlue-14]
	_ = x[White-15]
}

const _Color_name = "TransparentBlackGrayRedPinkDarkBrownBrownOrangeYellowGreenLightGreenDarkBlueBlueLightBlueSkyBlueWhite"

var _Color_index = [...]uint8{0, 11, 16, 20, 23, 27, 36, 41, 47, 53, 58, 68, 76, 80, 89, 96, 101}

func (i Color) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Color_index)-1 {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[idx]:_Color_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Triangle-0]
	_ = x[Sawtooth-1]
	_ = x[Pulse-2]
	_ = x[Noise-3]
}

const _Waveform_name = "TriangleSawtoothPulseNoise"

var _Waveform_index = [...]uint8{0, 8, 16, 21, 26}

func (i Waveform) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Waveform_index)-1 {
		return "Waveform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Waveform_name[_Waveform_index[idx]:_Waveform_index[idx+1]]
}
