// Code generated by "stringer -type Condition -trimprefix C_"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[C_Z-0]
	_ = x[C_NZ-1]
	_ = x[C_N-2]
	_ = x[C_NN-3]
	_ = x[C_P-4]
	_ = x[C_O-5]
	_ = x[C_NO-6]
	_ = x[C_A-7]
	_ = x[C_AE-8]
	_ = x[C_B-9]
	_ = x[C_BE-10]
	_ = x[C_G-11]
	_ = x[C_GE-12]
	_ = x[C_L-13]
	_ = x[C_LE-14]
	_ = x[NumConditions-15]
}

const _Condition_name = "ZNZNNNPONOAAEBBEGGELLENumConditions"

var _Condition_index = [...]uint8{0, 1, 3, 4, 6, 7, 8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 35}

func (i Condition) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Condition_index)-1 {
		return "Condition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Condition_name[_Condition_index[idx]:_Condition_index[idx+1]]
}
